exec-once = ags run
exec-once = firefox
exec-once = swaybg -i ~/media/images/wallpapers/skeleton.png

# Fix discord screensharing
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprland-session.target
